version: "3"

services:
  web:
    build: ./cool_app
    env_file: .env
    ports:
      - "127.0.0.1:8001:8001"
    links:
      - postgres:postgres
    command: python manage.py runserver 0.0.0.0:8001
  postgres:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./data:/data
volumes: 
  postgres:
