version: "3"

services:
  web:
    build: ./cool_app
    env_file: .env
    ports:
      - "127.0.0.1:8001:8001"
    volumes: 
      - ./cool_app:/code
    links:
      - postgres:postgres
    command: ./run_app.sh
  postgres:
    image: postgres:11
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
